### ISSUE TITLE
electron-builder config extension

### ISSUE THREAD

**Issue by KageyamaJie** [caoxiemeihao/electron-vite-react#24]
I tried to run the app with `npm run build` but wasn't able to build the app and rather it leads to opening the file `electron-builder.js`.
And I have read the docs on [https://www.electron.build/cli.html](url). Which it default to `.yml .json .json5` file extension.
So I'm wondering is there some extra configuration needed, to allow running electron-builder CLI with .js extension?

**Comment by KageyamaJie** [comment]
Found the reason [https://www.electron.build/configuration/configuration](url)

In the tip section stated 
> If you want to use js file, do not name it electron-builder.js. It will [conflict](https://github.com/electron-userland/electron-builder/issues/6227) with electron-builder package name.

Therefore, I renamed the file from `electron-builder.js` to `electron-builder.config.js` and it works fine when building for exe

**Comment by PAXANDDOS** [comment]
> > If you want to use js file, do not name it electron-builder.js. It will [conflict](https://github.com/electron-userland/electron-builder/issues/6227) with electron-builder package name.
> 
> Therefore, I renamed the file from `electron-builder.js` to `electron-builder.config.js` and it works fine when building for exe

It was actually named `electron-builder.config.js` from the beginning, I brought builder configuration in the js file but for some reason, it got renamed 😅 @caoxiemeihao you should probably rename it back

**Comment by caoxiemeihao** [comment]
@PAXANDDOS 😅 This time I was wrong.  
I use `.js` the sense of the file is that it supports comments.  

Now we have a PR https://github.com/electron-vite/electron-vite-react/pull/28 fix the problem. But I think `.json5` more friendly. 😄
